//{{NO_DEPENDENCIES}}
// Microsoft Visual C++ で生成されたインクルード ファイルです。
// 次で使用: WBS_cpp_win32.rc

#define IDS_APP_TITLE			103

#define IDR_MAINFRAME			128
#define IDD_WBSCPPWIN32_DIALOG	102
#define IDD_ABOUTBOX			103
#define IDM_ABOUT				104
#define IDM_EXIT				105
#define IDI_WBSCPPWIN32			107
#define IDI_SMALL				108
#define IDC_WBSCPPWIN32			109
#define IDC_MYICON				2

// WBS関連のリソースID
#define IDM_FILE_NEW			110
#define IDM_FILE_OPEN			111
#define IDM_FILE_SAVE			112
#define IDM_FILE_SAVE_AS		113
#define IDM_EDIT_ADD_TASK		120
#define IDM_EDIT_ADD_SUBTASK	121
#define IDM_EDIT_EDIT_TASK		122
#define IDM_EDIT_DELETE_TASK	123
#define IDM_VIEW_EXPAND_ALL		130
#define IDM_VIEW_COLLAPSE_ALL	131
#define IDM_EDIT_UNDO			140
#define IDM_EDIT_REDO			141
#define IDM_FILE_PRINT			150
#define IDM_FILE_PRINT_SETUP	151
#define IDM_HELP_CONTENTS		160
#define IDM_HELP_INDEX			161
#define IDM_HELP_SEARCH			162

// ダイアログID
#define IDD_TASK_EDIT			200
#define IDD_ABOUT				201
#define IDD_PREFERENCES			202
#define IDD_PRINT_SETTINGS		203

// コントロールID
#define IDC_TREE_WBS			1000
#define IDC_LIST_DETAILS		1001
#define IDC_EDIT_TASK_NAME		1010
#define IDC_EDIT_DESCRIPTION	1011
#define IDC_EDIT_START_DATE		1012
#define IDC_EDIT_END_DATE		1013
#define IDC_EDIT_ESTIMATED_HOURS 1014
#define IDC_EDIT_ACTUAL_HOURS	1015
#define IDC_COMBO_STATUS		1016
#define IDC_COMBO_PRIORITY		1017
#define IDC_EDIT_ASSIGNED_TO	1018
#define IDC_BUTTON_OK			1019
#define IDC_BUTTON_CANCEL		1020
#define IDC_STATIC_TEXT			1021
#define IDC_CHECK_REMINDER		1022
#define IDC_COMBO_FONT_SIZE	1023
#define IDC_EDIT_SEARCH			1024
#define IDC_BUTTON_SEARCH		1025
#define IDC_RADIO_TASK			1026
#define IDC_RADIO_PROJECT		1027

#ifndef IDC_STATIC
#define IDC_STATIC				-1
#endif
// 新しいオブジェクトの次の既定値
//
#ifdef APSTUDIO_INVOKED
#ifndef APSTUDIO_READONLY_SYMBOLS

#define _APS_NO_MFC					130
#define _APS_NEXT_RESOURCE_VALUE	210
#define _APS_NEXT_COMMAND_VALUE		32771
#define _APS_NEXT_CONTROL_VALUE		1021
#define _APS_NEXT_SYMED_VALUE		120
#endif
#endif
